//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcbooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Genre
    {
        public int Id { get; set; }
        public int Book_Id { get; set; }
        public int Genre_Id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
